#!/bin/bash 
# Use: tournament interface player1Folder player2Folder maxDepth timeout1 timeout2

#java -jar #(dirname "$0")"/Reversi.jar gui -human folder 6 0 0 
java -jar "$(dirname "$0")"/Reversi.jar "$1" "$2" "$3" "$4" "$5" "$6"

#java -cp "$(dirname $0)" Reversi "$1" "$2" "$3" "$4" "$5" "$6"
